# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Python Client Library for Web Time Series Service
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-04
        copyright            : (C) 2020 by INPE
        email                : brazildatacube@dpi.inpe.br
        git sha              : $Format:%H$
 ***************************************************************************/
"""

import os


# Class to configure global variables used in source code
class Config:
    """
    Base configuration for global variables

    Atributtes
        BASE_DIR(str) Returns app root path
    """
    BASE_DIR = os.path.abspath(os.path.dirname(__file__))
