"""
WTSS QGIS Plugin.

Python Client Library for Web Time Series Service.
Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/.
                              -------------------
begin                : 2019-05-04
git sha              : $Format:%H$
copyright            : (C) 2020 by INPE
email                : brazildatacube@dpi.inpe.br

This program is free software.

You can redistribute it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
"""


import os

from qgis.PyQt import QtWidgets, uic

FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'wtss_qgis_dialog_base.ui'))

class wtss_qgisDialog(QtWidgets.QDialog, FORM_CLASS):
    """Set up the user interface from Designer through FORM_CLASS.

    :param QDialog: QDialog
    :param FORM_CLASS: Set gui
    """

    def __init__(self, parent=None):
        """Build UI element.

        :param parent: None
        """
        super(wtss_qgisDialog, self).__init__(parent)
        self.setupUi(self)
